### ISSUE TITLE
Survey Satisfaction

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#1]
Need to move the no comment box closer on mobile

**Comment by krisgardner** [comment]
test

**Comment by krisgardner** [comment]
test

**Comment by krisgardner** [comment]
in p1851170254

**Comment by NitikaRaturi** [comment]
Hi Kris,

I have updated survey satisfaction question in below PID. You can test this now.

http://survey.euro.confirmit.com/wix/4/p1851170254.aspx?c=1&l=9&w=1&bk=99&pid=testID2
