### ISSUE TITLE
Single logo - make it work with single coded dummy

### ISSUE THREAD

**Issue by swat1gupta** [krisgardner/surveyDevelopment#15]
It currently works on MC dummy, need to update the script so that it works for SC dummy.

**Comment by swat1gupta** [comment]
It can be found in the following pnumber:
p1851468094
oSQ8
Kris - can you test it once for me?

**Comment by krisgardner** [comment]
@swat1gupta seems to work fine, can you add to p1851170254 :+1:

**Comment by swat1gupta** [comment]
added to the library

**Comment by krisgardner** [comment]
Please make it consistent with M24 as the boxes are so curved and selected border very thick!
