### ISSUE TITLE
Precodes - showing precode numbers in the test link

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#22]
@NitikaRaturi @sher-singh  can you let me know how much time and cost this will be?

**Comment by NitikaRaturi** [comment]
Hi Kris,

We have checked the feasibility of the request. Please find the time and cost below.

Time: 6-8 hours.
Cost: USD$100

Also I have created a dummy question. Please find the screenshot below.

![dummy1](https://cloud.githubusercontent.com/assets/2064384/17203707/929bb6a2-54be-11e6-8110-91786bdcbf2e.PNG)
