### ISSUE TITLE
Navigation buttons on mobile template

### ISSUE THREAD

**Issue by swat1gupta** [krisgardner/surveyDevelopment#27]
They are not aligned together when you try to type in something in the open text box. @NitikaRaturi - you fixed this for Cyan tracker. Can you fix it in the main template?
![screenshot_2016-07-22-16-05-53](https://cloud.githubusercontent.com/assets/16413758/17061557/fea54ef4-5026-11e6-9f0c-221ed0b4daa5.png)

**Comment by swat1gupta** [comment]
@NitikaRaturi - can you also let us know what you changed in the script to fix it?

**Comment by NitikaRaturi** [comment]
This is fixed in tesco also i have fixed this same in master template as well.

**Comment by krisgardner** [comment]
@swat1gupta  can you sign this one off and close when ready
