### ISSUE TITLE
Template Ability to switch to a different theme easily

### ISSUE THREAD

**Issue by swat1gupta** [krisgardner/surveyDevelopment#30]
Like we did for Tesco Insurance, can we have an easy way to switch to a different theme. This can be through:
a dummy
or a script to switch it

Can we please have a document for this as well?

**Comment by NitikaRaturi** [comment]
Hi Kris,

Dynamic theme change is possible. We don't need to change complete script but have to create a setup for background and font color change.

Cost: USD100.
Time : 3 days including testing.

Regards,
Nitika

**Comment by krisgardner** [comment]
@swat1gupta can you set this up to make it easier to switch in the template? 2 options, normal look & feel and white template (like prudential)

**Comment by krisgardner** [comment]
@swat1gupta did you manage to look into this one?

**Comment by krisgardner** [comment]
closing as there is another ticket ..open for this
