### ISSUE TITLE
Blocking windows phones

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#37]
Need to look into and then add into template when we have a solution

**Comment by swat1gupta** [comment]
This has been added in the template p1852711053
I need to check with Francisco if there is a way to make the message dynamic.

**Comment by krisgardner** [comment]
@swat1gupta checked and it's there, will leave open until we have investigated further

**Comment by krisgardner** [comment]
@swat1gupta this can be closed?

**Comment by swat1gupta** [comment]
yeah, that's fine. Thanks :)
