### ISSUE TITLE
Image Enlargement don't work in Firefox

### ISSUE THREAD

**Issue by swat1gupta** [krisgardner/surveyDevelopment#42]
For Hawkfire - Image Enlargement didn't work on Firefox,
Apsidata did something to fix it - this needs to be shared by them. 
Also, Image Enalrgement function needs to be fixed.

**Comment by NitikaRaturi** [comment]
Hi Swati,

I have already shared the same with Kris. Please confirm if code need to be shared on mail.

**Comment by swat1gupta** [comment]
Kris - can you confirm if this works fine?

**Comment by krisgardner** [comment]
we are using this now on some projects so seems to work fine. will close
