### ISSUE TITLE
Ranking - issue with ranking boxes

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#74]
@sher-singh for the ranking tool (RAN1 - p1852648011). We have this issue on galaxy note, any ideas?

![ranking](https://cloud.githubusercontent.com/assets/16320935/20883493/64a5ef02-bade-11e6-8506-984a1ac3af35.png)

**Comment by krisgardner** [comment]
@sher-singh any update on this one?

**Comment by sher-singh** [comment]
sorry Kris, i dont have galaxy note so not able to generate this issue...
