### ISSUE TITLE
Ranking - Extra padding on mobile (android) when portrait

### ISSUE THREAD

**Issue by eniokuwobi** [krisgardner/surveyDevelopment#75]
![image](https://cloud.githubusercontent.com/assets/23660636/21262802/260788c2-c38b-11e6-8339-40492818edb8.png)

**Comment by sher-singh** [comment]
please share pid and qid

**Comment by eniokuwobi** [comment]
PID = p1855108305
QID =  T5 & T6

**Comment by eniokuwobi** [comment]
@sher-singh PID = p1855108305
QID = T5 & T6

**Comment by sher-singh** [comment]
Kris: please give me permission on this pnumber...

**Comment by krisgardner** [comment]
@sher this is done now

**Comment by sher-singh** [comment]
Kris: is there any specific reason why we have added group header on T5 and T6 questions?
