### ISSUE TITLE
Survey template master amends - scripts/questions

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#8]
- [x] add survey satisfaction questions
- [x] add total quota and qf script
- [ ] multi grid question - SQ5 roulette
- [ ] suvey sat question - roulette
- [ ] drop down question - roulette, region
- [ ] gender question - roulette
  -[ ] add any other fixes to template from the roulette log

**Comment by NitikaRaturi** [comment]
Hi Kris,

Please confirm pid on which these changes need to be done. Currently i have implemented the same in custom question survey

http://survey.euro.confirmit.com/wix/4/p1851170254.aspx?c=1&l=9&w=1&bk=99&pid=testID2

**Comment by krisgardner** [comment]
#8 is assigned to me, so don’t worry about this one! And yes p number is correct. Let’s use this for changes.

**Comment by krisgardner** [comment]
@NitikaRaturi i will update survey satisfaction with slider tool when its ready
