### ISSUE TITLE
Grids -  font size is different for options

### ISSUE THREAD

**Issue by krisgardner** [krisgardner/surveyDevelopment#9]
![capture](https://cloud.githubusercontent.com/assets/16320935/16690984/8060069c-4522-11e6-9ef1-794de45fdfb0.PNG)

**Comment by krisgardner** [comment]
works in SQ5 - p1852107546 but needs to be added to main template

**Comment by NitikaRaturi** [comment]
I have added this same in p1851170254
![capture](https://cloud.githubusercontent.com/assets/2064384/16774892/9d624294-487b-11e6-90c8-e5121ddab6bf.PNG)

**Comment by krisgardner** [comment]
@NitikaRaturi would you be able to remove some padding from the left, use the space on the left so the grid is a little larger? Also can you have a tiny bit of right padding so the grid doesn't look like its going off the page?

**Comment by NitikaRaturi** [comment]
Sure i will look into it.

**Comment by NitikaRaturi** [comment]
Please find  the screenshot attached.
Landscape: 
![gridlandscape](https://cloud.githubusercontent.com/assets/2064384/16832714/2783587a-49c9-11e6-8986-68a096b13749.png)

Portrait
![gridportrait](https://cloud.githubusercontent.com/assets/2064384/16832727/3bdf1e80-49c9-11e6-854c-91e42c7ca831.png)

Normal

![gridnormal](https://cloud.githubusercontent.com/assets/2064384/16832735/44599edc-49c9-11e6-9a2f-3b571f867690.png)

**Comment by krisgardner** [comment]
@NitikaRaturi yep this looks good now on desktop. font sizes are consistent.
